version: '3.8'

services:
  backend:
    build: ./backend
    container_name: genresume-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run start"

  frontend:
    build: ./frontend
    container_name: genresume-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm start"
    depends_on:
      - backend
